[package]
name = "discord_woofer"
version = "0.2.0"
edition = "2018"
authors = ["daniel lu <daniel@lawrence.lu>"]

[dependencies]
anyhow = "1.0"
lazy_static = "1.4.0"
rand = "0.8.3"
regex = "1.4.3"
reqwest = "0.11.0"
url = "2.2.0"
serenity = { version = "0.10", default-features = false, features = ["client", "gateway", "rustls_backend", "model",  "cache"] }
serde = "1.0"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
shakmaty = "0.17.2"
